# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pos.models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20170422_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Store')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('delivery_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('store_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('supplier_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('image', models.FileField(upload_to=pos.models.product_directory_path)),
                ('type', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Supplier'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Product'),
        ),
    ]
