# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20170422_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_hour',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='provee', max_length=80),
            preserve_default=False,
        ),
    ]
