# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_auto_20170422_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='client',
        ),
        migrations.AddField(
            model_name='sale',
            name='client_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='client_gender',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
